# Generated by Django 4.0.3 on 2022-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_to',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
