# Generated by Django 4.0.3 on 2022-04-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0014_alter_post_category_alter_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet_test',
            field=models.CharField(default='click link above to read the blog post', max_length=255),
        ),
    ]
