# Generated by Django 4.0.3 on 2022-04-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0015_post_snippet_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet_test',
            field=models.CharField(max_length=255),
        ),
    ]
