# Generated by Django 4.0.3 on 2022-04-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0016_alter_post_snippet_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='heder_image',
            field=models.ImageField(blank=True, null=True, upload_to='imaged/'),
        ),
    ]
