# Generated by Django 4.0.3 on 2022-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theBlog', '0017_post_heder_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heder_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
